#export ANDROID_NDK_HOME="/opt/android-ndk-r21"
#export ANDROID_ROOT_PATH="/home/fanghui/share_home2/android-10-5.4"
cmake	-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
      -DANDROID_NDK=$ANDROID_NDK_HOME \
      -DANDROID_ABI=arm64-v8a \
      -DANDROID_TOOLCHAIN=clang \
      -DANDROID_PLATFORM=android-29 \
      -DANDROID_ALLOW_UNDEFINED_SYMBOLS=1 \
      -DCMAKE_SYSTEM_NAME=ANDROID \
      -DANDROID_ROOT=$ANDROID_ROOT_PATH \
      -DCMAKE_BUILD_TYPE=debug -DISP_VERSION=ISP8000NANO_V1802 -DPLATFORM=ARM64 -DAPPMODE=V4L2 -DQTLESS=1 -DFULL_SRC_COMPILE=1 -DWITH_DWE=1 -DWITH_DRM=1 -DSERVER_LESS=1 -DSUBDEV_V4L2=1 -DENABLE_IRQ=1 .. -Wno-dev

